# https://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/
version: 5.1.0
variant: default
head:
  favicon: /about/github.png
  open_graph:
    type: blog
navbar:
  menu:
    首页: /
    分类: /categories
    目录: /catalog
    留言板: /about
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/kivihub/kivihub-blog
footer:
  copyright: 非学无以广才，非志无以成学
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/kivihub/kivihub-blog
article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: "unfolded"
  readtime: true
  update_time: false
search:
  type: insight
  index_pages: true
sidebar:
  left:
    sticky: true
  right:
    sticky: false
# https://ppoffice.github.io/hexo-theme-icarus/Widgets/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E6%8C%82%E4%BB%B6/
widgets:
  - position: left
    type: profile
    author: Kivi
    location: Beijing
    avatar: /about/avatar.jpeg
    avatar_rounded: false
    follow_link: https://github.com/kivihub
  - position: left
    type: categories
#  - position: right
#    type: recent_posts
  - position: right
    type: archives
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
  animejs: true
  back_to_top: true
  busuanzi: true
  gallery: true
  katex: false
  mathjax: false
  outdated_browser: false
  pjax: true
  progressbar: true
  baidu_analytics:
    tracking_id: 18875f49bd2f905d572a26a7796c193b
  google_analytics:
    tracking_id: G-H16FQ6QJL5
# https://ppoffice.github.io/hexo-theme-icarus/Plugins/Comment/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E7%94%A8%E6%88%B7%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/#Giscus
comment:
  type: giscus
  repo: kivihub/kivihub-blog
  repoId: MDEwOlJlcG9zaXRvcnkzMjk3MjM2NDk=
  category: Announcements
  categoryId: DIC_kwDOE6cvAc4CmtLD
  mapping: pathname
  strict: false
  reactionsEnabled: false
  emitMetadata: false
  inputPosition: top
  theme: noborder_light
  lang: zh-CN
  lazy: true
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
